name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - master
      - feature/github_actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: doxygen-github-pages-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
